# Exceptions

```csharp
using System;
using System.Globalization;

namespace Editor_de_texto {
    internal class Program {
        static void Main(string[] args) {

            var arr = new int[3];

            try { // tente rodar o for, se caso der algo de errado ele passa para o catch

                //for (var index = 0; index < 10; index++) {

                //    Console.WriteLine(arr[index]); //  gerou este erro System.IndexOutOfRangeException, pois estamos pedindo para ele percorrer 11 arrays, sendo que ele tem somente 4 arrays
                //}
                Cadastrar("");
            } catch (IndexOutOfRangeException ex) { // fora de index gera esse erro 
                Console.WriteLine(ex.InnerException);
                Console.WriteLine(ex.Message);
                Console.WriteLine("não encontrei o indice na lista");

            } catch (ArgumentNullException ex) {  // aqui ele verifica se o parametro esta nulo, caso seja true ele mostra a mensagem de erro abaixo ()
                Console.WriteLine(ex.InnerException); // exibi tambem uma mensagem de erro e visualize informacoes detalhadas sobre a raiz do problema
                Console.WriteLine(ex.Message); // exibi a mensagem de erro na tela 
                Console.WriteLine("falha ao cadastrar texto");
            } catch (MinhaException ex) {  
                Console.WriteLine(ex.InnerException); 
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.QuantoAconteceu);
                Console.WriteLine("exceção customizada");
            } catch (Exception ex) {  // imprima esssa informacao caso algo der errado (sempre tem essa ordem de try em primeiro e depois o catch) se gerar um erro desconhecido ou generico roda essa codição
                Console.WriteLine(ex.InnerException); // exibi tambem uma mensagem de erro e visualize informacoes detalhadas sobre a raiz do problema
                Console.WriteLine(ex.Message); // exibi a mensagem de erro na tela 
                Console.WriteLine("Ops algo deu errado!!");
            }
        }
        static void Cadastrar(String texto) {
             if (string.IsNullOrEmpty(texto))//  se caso a string for nula ou vazia vai gerar erro
                throw new MinhaException(DateTime.Now);
        }

        public class MinhaException : Exception { // foi feito uma classe em herança

            public MinhaException(DateTime date) {  // foi realizado aqui o metodo construtor

                QuantoAconteceu = date;  // é atribuido o valor do date para a propriedade "QuandoAconteceu"
            }
            public DateTime QuantoAconteceu { get; set; } /*isso é uma propriedade de um objeto, que utiliza a classe DateTime para trabalhar com datas e horários.*/
        }
    
    }
}
```